#!/usr/bin/env bash
#
# Forces the target SDK of the Bubblewrap-generated Android project.
#
# Bubblewrap pins whatever target SDK its release shipped with, while Play
# enforces a floor that moves every year and rejects uploads below it. Rather
# than wait for a Bubblewrap release, rewrite the generated Gradle files after
# `bubblewrap init` and before `bubblewrap build`.
#
#   bun run android:target-sdk           # uses TARGET_SDK below
#   bun run android:target-sdk -- 36     # or an explicit level
#
# Only build.gradle files generated by Bubblewrap are touched; nothing here is
# committed, because the Android project is generated fresh on every run.

set -euo pipefail

TARGET_SDK="${1:-35}"
COMPILE_SDK="${COMPILE_SDK:-$TARGET_SDK}"
PROJECT_DIR="${ANDROID_PROJECT_DIR:-$(pwd)}"

if ! [[ "$TARGET_SDK" =~ ^[0-9]+$ ]]; then
   echo "Target SDK must be an integer (got \"$TARGET_SDK\")." >&2
   exit 2
fi

mapfile -t gradle_files < <(find "$PROJECT_DIR" -maxdepth 3 -name "build.gradle" -not -path "*/node_modules/*")

if [ "${#gradle_files[@]}" -eq 0 ]; then
   echo "No build.gradle found under $PROJECT_DIR — run \`bubblewrap init\` first." >&2
   exit 1
fi

changed=0

for gradle in "${gradle_files[@]}"; do
   if grep -qE "targetSdkVersion|compileSdkVersion" "$gradle"; then
      sed -i -E \
         -e "s/targetSdkVersion[[:space:]]+[0-9]+/targetSdkVersion $TARGET_SDK/" \
         -e "s/compileSdkVersion[[:space:]]+[0-9]+/compileSdkVersion $COMPILE_SDK/" \
         "$gradle"
      echo "✓ $gradle → targetSdk $TARGET_SDK, compileSdk $COMPILE_SDK"
      changed=$((changed + 1))
   fi
done

if [ "$changed" -eq 0 ]; then
   echo "No targetSdkVersion/compileSdkVersion declarations found — did the Bubblewrap layout change?" >&2
   exit 1
fi

echo
echo "Rewrote $changed Gradle file(s)."
