/**
 * semantic-release: version, changelog and GitHub release, driven entirely by
 * the conventional-commit history that commitguard enforces on commit-msg.
 *
 * Runs only from `main`, only in CI (see .github/workflows/release.yml). The
 * package is private, so npm publishing is off — the npm plugin is kept purely
 * to write the new version into package.json, which android:version then reads.
 */
export default {
   branches: ["main"],

   plugins: [
      [
         "@semantic-release/commit-analyzer",
         {
            preset: "conventionalcommits",
            releaseRules: [
               { type: "perf", release: "patch" },
               { type: "refactor", release: "patch" },
               { type: "build", release: "patch" },
               { type: "docs", scope: "readme", release: "patch" },
               { type: "chore", release: false },
               { type: "ci", release: false },
               { type: "test", release: false },
               { type: "style", release: false },
            ],
         },
      ],
      [
         "@semantic-release/release-notes-generator",
         {
            preset: "conventionalcommits",
            presetConfig: {
               types: [
                  { type: "feat", section: "Features" },
                  { type: "fix", section: "Bug Fixes" },
                  { type: "perf", section: "Performance" },
                  { type: "refactor", section: "Refactoring" },
                  { type: "build", section: "Build System" },
                  { type: "docs", section: "Documentation", hidden: false },
                  { type: "chore", hidden: true },
                  { type: "ci", hidden: true },
                  { type: "test", hidden: true },
                  { type: "style", hidden: true },
               ],
            },
         },
      ],
      [
         "@semantic-release/changelog",
         {
            changelogFile: "CHANGELOG.md",
            changelogTitle: "# Changelog\n\nAll notable changes to this project are documented here. This file is\ngenerated by semantic-release from the conventional commit history — do not\nedit it by hand.",
         },
      ],
      [
         "@semantic-release/npm",
         {
            // The site is not published to npm; this only bumps package.json.
            npmPublish: false,
         },
      ],
      [
         "@semantic-release/git",
         {
            assets: ["CHANGELOG.md", "package.json"],
            message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}",
         },
      ],
      [
         "@semantic-release/github",
         {
            successComment: false,
            failComment: false,
            releasedLabels: false,
         },
      ],
   ],
};
