#!/usr/bin/env bash
#
# SEO verification smoke test for Devanilayam (Nuxt SEO suite + i18n).
#
# Boots the production build locally and asserts every SEO surface actually
# renders in the SSR HTML: robots.txt, the sitemap, per-route meta/OG/Twitter,
# canonical, hreflang alternates, JSON-LD, and the OG image itself.
#
# Usage:
#   scripts/seo/verify.sh                 # build if needed, boot server, check
#   BUILD=1 scripts/seo/verify.sh         # force a fresh build first
#   PORT=4000 scripts/seo/verify.sh       # use a different local port
#   ROUTES="/en /te" scripts/seo/verify.sh              # check specific routes
#   BASE_URL=https://foo.vercel.app scripts/seo/verify.sh
#                                         # check a remote deploy (no build/boot)
#
# Exit code = number of failed checks (0 = all green).

set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

PORT="${PORT:-3220}"
SERVER_PID=""

# The locales the site ships, in the order the sitemap and hreflang list them.
LOCALES="${LOCALES:-en te hi}"

# One route per page type, so every template's metadata is asserted, plus each
# locale root so the hreflang cluster is checked in all three. The content
# routes are read out of the sitemap at runtime rather than hardcoded — the
# server already enumerates every sloka, ashtotara and blog for the sitemap
# (server/api/__sitemap__/urls.ts), so a hand-kept list here would drift the
# moment content is added.
SAMPLE_PER_SECTION="${SAMPLE_PER_SECTION:-1}"

# ── pretty output ────────────────────────────────────────────────────────────
if [[ -t 1 ]]; then
   G=$'\e[32m'; R=$'\e[31m'; Y=$'\e[33m'; C=$'\e[36m'; D=$'\e[2m'; B=$'\e[1m'; X=$'\e[0m'
else
   G=""; R=""; Y=""; C=""; D=""; B=""; X=""
fi
PASS=0; FAIL=0

pass()    { printf "  ${G}✔${X} %s\n" "$1"; PASS=$((PASS + 1)); }
fail()    { printf "  ${R}✗${X} %s${D} — %s${X}\n" "$1" "$2"; FAIL=$((FAIL + 1)); }
warn()    { printf "  ${Y}!${X} %s\n" "$1"; }
section() { printf "\n${B}%s${X}\n" "$1"; }

# Nitro content-negotiates: without a browser-like Accept header it answers
# error routes with JSON instead of the rendered error page, so a check that
# omits this tests something no crawler ever sees.
ACCEPT_HTML="text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"

fetch_html() { curl -s -H "Accept: $ACCEPT_HTML" "$@"; }

# assert_contains "<desc>" "<content>" "<regex>"
assert_contains() {
   if grep -qiE -- "$3" <<<"$2"; then pass "$1"; else fail "$1" "missing: $3"; fi
}

# assert_absent "<desc>" "<content>" "<regex>"
assert_absent() {
   if grep -qiE -- "$3" <<<"$2"; then fail "$1" "unexpected: $3"; else pass "$1"; fi
}

# ── server lifecycle ─────────────────────────────────────────────────────────
cleanup() {
   [[ -n "$SERVER_PID" ]] && kill "$SERVER_PID" 2>/dev/null
}
trap cleanup EXIT INT TERM

if [[ -n "${BASE_URL:-}" ]]; then
   BASE="${BASE_URL%/}"
   section "Target: ${C}${BASE}${X} ${D}(remote — no build/boot)${X}"
else
   BASE="http://127.0.0.1:${PORT}"
   if [[ "${BUILD:-0}" == "1" || ! -f .output/server/index.mjs ]]; then
      printf "${D}Building production output…${X}\n"
      if ! bun run build > /tmp/seo-build.log 2>&1; then
         printf "${R}Build failed.${X} See /tmp/seo-build.log\n"; tail -20 /tmp/seo-build.log; exit 1
      fi
   fi
   printf "${D}Starting server on :%s …${X}\n" "$PORT"
   PORT="$PORT" HOST=127.0.0.1 node .output/server/index.mjs > /tmp/seo-server.log 2>&1 &
   SERVER_PID=$!
   ready=0
   for _ in $(seq 1 60); do
      if curl -sf -o /dev/null "$BASE/"; then ready=1; break; fi
      sleep 1
   done
   if [[ "$ready" != "1" ]]; then
      printf "${R}Server never became ready.${X} See /tmp/seo-server.log\n"; tail -20 /tmp/seo-server.log; exit 1
   fi
   section "Target: ${C}${BASE}${X}"
fi

# ── fetch once, reuse ────────────────────────────────────────────────────────
ROBOTS="$(curl -s "$BASE/robots.txt")"
# Multi-locale, so @nuxtjs/sitemap serves an index that fans out to a file per
# language; follow it and concatenate so route membership can be checked once.
SITEMAP_INDEX="$(curl -sL "$BASE/sitemap.xml")"
SITEMAP="$SITEMAP_INDEX"

for child in $(grep -oE "<loc>[^<]*sitemap[^<]*</loc>" <<<"$SITEMAP_INDEX" \
   | sed -E 's#</?loc>##g' | sed -E "s#^https?://[^/]+##"); do
   SITEMAP+=$'\n'"$(curl -s "$BASE$child")"
done

# ── robots ───────────────────────────────────────────────────────────────────
section "robots.txt"
assert_contains "generated by nuxt-robots"  "$ROBOTS" "nuxt-robots"
assert_contains "references the sitemap"    "$ROBOTS" "Sitemap: https?://"
assert_contains "site is indexable"         "$ROBOTS" "User-agent: \*"
assert_absent   "no malformed locale rules" "$ROBOTS" "/undefined/"

# The site is meant to be readable by AI assistants, not just search engines.
section "AI crawler policy"
for bot in GPTBot ClaudeBot PerplexityBot Google-Extended OAI-SearchBot; do
   assert_contains "$bot is addressed" "$ROBOTS" "User-agent: $bot"
done

# ── sitemap ──────────────────────────────────────────────────────────────────
section "sitemap"
assert_contains "sitemap served"        "$SITEMAP_INDEX" "<urlset|<sitemapindex"
assert_contains "sitemap has entries"   "$SITEMAP" "<loc>https?://"

for locale in $LOCALES; do
   assert_contains "sitemap covers /$locale" "$SITEMAP" "<loc>[^<]*/$locale(/|<)"
done

# ── build the route list ─────────────────────────────────────────────────────
# Locale roots always, plus a sample of each content section from the sitemap.
if [[ -n "${ROUTES:-}" ]]; then
   CHECK_ROUTES="$ROUTES"
else
   CHECK_ROUTES=""
   for locale in $LOCALES; do
      CHECK_ROUTES+=" /$locale"
   done
   ALL_PATHS="$(grep -oE "<loc>[^<]*</loc>" <<<"$SITEMAP" \
      | sed -E 's#</?loc>##g' | sed -E "s#^https?://[^/]+##" | sort -u)"
   CHECK_ROUTES+=" /en/about"
   for pattern in "/en/slokas$" "/en/slokas/[^/]*$" "/en/slokas/[^/]*/[^/]*$" \
      "/en/ashtotaras$" "/en/ashtotaras/[^/]*$" "/en/blogs$" "/en/blogs/[^/]*$" \
      "/te/slokas/[^/]*/[^/]*$" "/hi/blogs/[^/]*$"; do
      CHECK_ROUTES+=" $(grep -E "$pattern" <<<"$ALL_PATHS" | head -"$SAMPLE_PER_SECTION" | tr '\n' ' ')"
   done
fi

# ── per-route checks ─────────────────────────────────────────────────────────
for route in $CHECK_ROUTES; do
   section "route ${C}${route}${X}"
   HTML="$(fetch_html "$BASE$route")"

   assert_contains "has <title>"          "$HTML" "<title>[^<]+</title>"
   assert_contains "meta description"     "$HTML" "name=\"description\" content=\"[^\"]+\""
   assert_contains "canonical URL"        "$HTML" "rel=\"canonical\""
   assert_contains "og:title"             "$HTML" "property=\"og:title\""
   assert_contains "og:description"       "$HTML" "property=\"og:description\""
   assert_contains "og:image"             "$HTML" "property=\"og:image\""
   assert_contains "twitter summary card" "$HTML" "name=\"twitter:card\" content=\"summary_large_image\""
   assert_contains "schema.org JSON-LD"   "$HTML" "application/ld\+json"
   assert_contains "renders an <h1>"      "$HTML" "<h1"

   # Multi-locale: every page must annotate its alternates, including x-default,
   # and declare the language of the document it is actually serving.
   route_locale="$(sed -E 's#^/([a-z]{2})(/.*)?$#\1#' <<<"$route")"
   # useLocaleHead emits the full BCP-47 tag (en-US, te-IN, hi-IN), so match the
   # language subtag and allow an optional region rather than demanding a bare code.
   assert_contains "declares lang=\"$route_locale\"" "$HTML" "<html[^>]*lang=\"$route_locale(-[A-Za-z]+)?\""
   assert_contains "hreflang x-default"   "$HTML" "hreflang=\"x-default\""
   for locale in $LOCALES; do
      assert_contains "hreflang alternate ($locale)" "$HTML" "rel=\"alternate\"[^>]*hreflang=\"$locale\""
   done

   assert_contains "listed in sitemap"    "$SITEMAP" "<loc>[^<]*${route%/}/?</loc>"

   # SSR is the whole point: an empty shell means crawlers see nothing.
   text_len="$(sed -e 's/<[^>]*>/ /g' <<<"$HTML" | tr -s ' \n' ' ' | wc -c)"
   if [[ "$text_len" -gt 500 ]]; then
      pass "server-rendered text present (${text_len} chars)"
   else
      fail "server-rendered text present" "only ${text_len} chars — is SSR on?"
   fi

   # Every JSON-LD block must parse, or Google discards it silently.
   if jsonld_blocks="$(bun scripts/lib/check-jsonld.mjs <<<"$HTML")"; then
      pass "JSON-LD parses (${jsonld_blocks} block(s))"
   else
      fail "JSON-LD parses" "no blocks, or one is malformed"
   fi

   # The OG card must actually render, not just be linked.
   OG_PATH="$(grep -oiE 'property="og:image" content="[^"]*"' <<<"$HTML" \
      | sed -E 's/.*content="([^"]*)".*/\1/' | sed -E 's#^https?://[^/]+##' | head -1)"
   if [[ -z "$OG_PATH" ]]; then
      fail "og:image URL found" "no og:image meta tag"
   else
      read -r OG_CODE OG_TYPE OG_SIZE < <(curl -s -o /dev/null -w "%{http_code} %{content_type} %{size_download}" "$BASE$OG_PATH")
      if [[ "$OG_CODE" == "200" && "$OG_TYPE" == image/png* && "${OG_SIZE:-0}" -gt 1000 ]]; then
         pass "OG card renders PNG (${OG_SIZE} bytes)"
      else
         fail "OG card renders PNG" "code=$OG_CODE type=$OG_TYPE size=${OG_SIZE:-0}"
      fi

      # Cards are rendered per route; if every page reports the same URL, the
      # per-page generation has silently fallen back to one static image.
      if [[ -n "${SEEN_OG_PATHS:-}" ]] && grep -qxF "$OG_PATH" <<<"${SEEN_OG_PATHS}"; then
         fail "the OG card is unique to this route" "same image as an earlier route ($OG_PATH)"
      else
         pass "the OG card is unique to this route"
         SEEN_OG_PATHS="${SEEN_OG_PATHS:-}${OG_PATH}"$'"'"'\n'"'"'
      fi
   fi
done

# ── negative checks ──────────────────────────────────────────────────────────
# A soft-404 (missing content answered with HTTP 200) gets a site demoted.
section "error handling"
MISSING_CODE="$(fetch_html -o /dev/null -w "%{http_code}" "$BASE/en/slokas/nonexistent/xyz")"
if [[ "$MISSING_CODE" == "404" ]]; then
   pass "missing content returns HTTP 404"
else
   fail "missing content returns HTTP 404" "got HTTP $MISSING_CODE (soft-404)"
fi

MISSING_HTML="$(fetch_html "$BASE/en/slokas/nonexistent/xyz")"
assert_contains "error page is noindex" "$MISSING_HTML" "name=\"robots\"[^>]*noindex"

# Policy pages are legal boilerplate and should not compete for rankings.
POLICY_HTML="$(fetch_html "$BASE/en/policies/privacy-policy")"
assert_contains "policy pages are noindex" "$POLICY_HTML" "name=\"robots\"[^>]*noindex"

# ── security headers ─────────────────────────────────────────────────────────
# Hardening rather than ranking, but a missing CSP or HSTS is the kind of
# regression nobody notices until it matters.
section "security headers"
HEADERS="$(curl -sI -H "Accept: $ACCEPT_HTML" "$BASE/en" | tr "A-Z" "a-z")"

for header in strict-transport-security x-content-type-options referrer-policy \
   content-security-policy permissions-policy x-frame-options; do
   assert_contains "$header is set" "$HEADERS" "^$header:"
done

assert_contains "CSP forbids framing"  "$HEADERS" "frame-ancestors 'none'"
assert_contains "CSP forbids plugins"  "$HEADERS" "object-src 'none'"
assert_contains "CSP pins base-uri"    "$HEADERS" "base-uri 'self'"

# ── sitelinks search box ─────────────────────────────────────────────────────
# The SearchAction is only worth declaring if the endpoint it names actually
# answers — a template pointing at a dead route is worse than none.
section "site search"
HOME_HTML="$(fetch_html "$BASE/en")"
assert_contains "WebSite declares a SearchAction" "$HOME_HTML" "SearchAction"
assert_contains "SearchAction names a query template" "$HOME_HTML" "search_term_string"

SEARCH_HTML="$(fetch_html "$BASE/en/search?q=hanuman")"
if grep -q 'class="search-result__title"' <<<"$SEARCH_HTML"; then
   pass "the search endpoint returns server-rendered results"
else
   fail "the search endpoint returns server-rendered results" "no results in the HTML for ?q=hanuman"
fi

assert_contains "search results are noindex" "$SEARCH_HTML" "name=\"robots\"[^>]*noindex"
assert_absent   "search is kept out of the sitemap" "$SITEMAP" "<loc>[^<]*/search</loc>"

# A prerendered /search would serve the same empty page for every query.
EMPTY_SEARCH="$(fetch_html "$BASE/en/search")"
if grep -q 'class="search-result__title"' <<<"$EMPTY_SEARCH"; then
   fail "an empty query returns no results" "results leaked from a prerendered page"
else
   pass "an empty query returns no results"
fi

# ── dead links ───────────────────────────────────────────────────────────────
section "navigation"
for route in /en /en/about; do
   PAGE="$(fetch_html "$BASE$route")"
   assert_absent "$route has no placeholder href=\"#\" links" "$PAGE" "href=\"#\""
done

# ── summary ──────────────────────────────────────────────────────────────────
printf "\n${B}Summary${X}  ${G}%d passed${X}  ${R}%d failed${X}\n" "$PASS" "$FAIL"
exit "$FAIL"
